version: "{build}"
skip_branch_with_pr: true
environment:
  matrix:
  - PYTHON: c:\python35
  - PYTHON: c:\python35-x64
  - PYTHON: c:\python36
  - PYTHON: c:\python36-x64
build: off
install:
- cmd: '%PYTHON%\python.exe -m pip install -r requirements.txt'
test_script:
- cmd: '%PYTHON%\python.exe -m unittest discover'
